function search4()
{if(form1.abc0.checked)
window.open("http://search.iask.com/cgi-bin/search/search.cgi?_searchkey="+form1.key.value,"mspg0");if(form1.abc1.checked)
window.open("http://www.sogou.com/site?query="+form1.key.value,"mspg1");if(form1.abc2.checked)
window.open("http://cn.search.yahoo.com/search/cn?p="+form1.key.value,"mspg2");if(form1.abc3.checked)
window.open("http://www.skycn.com/search.php?sor=00&ss_name="+form1.key.value,"mspg3");if(form1.abc4.checked)
window.open("http://www.google.cn/search?client=pub-7100890577751553&hl=zh-CN&q="+form1.key.value,"mspg4");if(form1.abc5.checked)
window.open("http://search.yahoo.com/bin/search?p="+form1.key.value,"mspg5");if(form1.abc6.checked)
window.open("http://www.baidu.com/s?tn=19820726_pg&word="+form1.key.value,"mspg6");if(form1.abc7.checked)
window.open("http://mp3search.baidu.com/wstsearch?tn=baiduaaa&ct=134217728&lm=-1&rn=&word="+form1.key.value,"mspg7");if(form1.abc8.checked)
window.open("http://search.sogua.com/search/search.asp?fmp3=1&frm=1&fwma=1&fasf=1&go.x=25&go.y=19&key="+form1.key.value,"mspg8");if(form1.abc9.checked)
window.open("http://mp3.baidu.com/m?f=ms&rn=10&tn=baidump3lyric&ct=150994944&word="+form1.key.value,"mspg9");if(form1.abc10.checked)
window.open("http://pic.sina.com.cn/cgi-bin/retr/search?query="+form1.key.value,"mspg10");if(form1.abc11.checked)
window.open("http://www.baidu.com/i?ct=201326592&cl=2&lm=-1&tn=baiduimage&word="+form1.key.value,"mspg11");if(form1.abc12.checked)
window.open("http://www.gougou.com/search?search="+form1.key.value,"mspg12");if(form1.abc13.checked)
window.open("http://flash.zhongsou.com/zsflash.cgi?myselectvalue=2&tn=flash&ct=33554432&lm=&word="+form1.key.value,"mspg13");if(form1.abc14.checked)
window.open("http://www.yisou.com/search?p="+form1.key.value,"mspg14");if(form1.abc15.checked)
window.open("http://p.zhongsou.com/p?dt=1&pt=1&w="+form1.key.value,"mspg15");if(form1.abc16.checked)
window.open("http://www.5idsj.com/php/search.php?keyword="+form1.key.value,"mspg16");if(form1.abc17.checked)
window.open("http://www.feedss.com/html/1/1/"+form1.key.value,"mspg17");if(form1.abc18.checked)
window.open("http://so.guoxue.com/index.html?KeyWord="+form1.key.value,"mspg18")
return false;}